charts/urls.py
from django.urls import path

from . import views

app_name = 'charts'
urlpatterns = [
    path('', views.charts, name='charts'),
    path('<int:diagram_id>/configure', views.configure, name="configure"),
    path('<int:diagram_id>/setup', views.setup, name="setup"),
    path('<int:diagram_id>/pareto', views.pareto_chart, name="pareto_chart"),
]

pareto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('charts.urls')),
    path("admin/", admin.site.urls),
]

charts/models.py
from django.db import models


class Diagram(models.Model):
    diagram_name = models.CharField(max_length=15)
    fields = models.CharField(max_length=5000, default='')
    ready = models.BooleanField(default=False)

    def __str__(self):
        return self.diagram_name

charts/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Diagram


# Create your views here.
def charts(request):
    diagrams = get_list_or_404(Diagram)
    return render(request, 'charts/index.html', {'diagrams': diagrams})


def configure(request, diagram_id):
    diagram = get_object_or_404(Diagram, pk=diagram_id)
    return render(request, 'charts/configure.html', {'diagram': diagram})


def pareto_chart(request, diagram_id):
    diagram = get_object_or_404(Diagram, pk=diagram_id)
    items = diagram.fields.split('\r\n')

    def mapper(w):
        return w.split('=')

    data = list(map(mapper, items))
    return render(request, 'charts/pareto.html', {'diagram': diagram, 'items': data})


def setup(request, diagram_id):
    diagram = get_object_or_404(Diagram, pk=diagram_id)
    try:
        key = request.POST['values']
    except (KeyError, Diagram.DoesNotExist):
        return render(request, 'polls/configure.html', {
            'error-message': 'Что-то пошло не так'
        })
    else:
        diagram.fields = key
        diagram.save()
        return redirect('charts:pareto_chart', diagram_id=diagram_id)

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Diagram


# Create your views here.
def index(request):
    diagrams = get_list_or_404(Diagram)
    return render(request, 'polls/index.html', {'diagrams': diagrams})


def diagram_fill(request, diagram_id):
    diagram = get_object_or_404(Diagram, pk=diagram_id)
    return render(request, 'polls/diagram_fill.html', {'diagram': diagram})


def diagram_view(request, diagram_id):
    diagram = get_object_or_404(Diagram, pk=diagram_id)
    items = diagram.fields.split(',')

    def mapper(w):
        return w.split('=')

    data = list(map(mapper, items))
    return render(request, 'polls/diagram_view.html', {'diagram': diagram, 'items': data})


def diagram_set(request, diagram_id):
    diagram = get_object_or_404(Diagram, pk=diagram_id)
    try:
        key = request.POST['values']
    except (KeyError, Diagram.DoesNotExist):
        return render(request, 'polls/error.html')
    else:
        diagram.fields = key
        diagram.save()
        return redirect('polls:diagram_view', diagram_id=diagram_id)

charts/templates/charts/configure.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'charts/configure.css' %}">
    <title>Добавление данных для графика</title>
</head>
<body>
<form action="{% url 'charts:setup' diagram.id %}" method="post">
{% csrf_token %}
    {% if error_message %}
    <h1>{{ error_message }}</h1>
    {% elif diagram.ready == False %}
    <h1>Этот вид графиков еще не доступен</h1>
    <a href="{% url 'charts:charts' %}">Вернуться в меню</a>
    {% else %}
    <h1>Добавьте данные для {{ diagram.diagram_name }}</h1>
    <h3>Пропишите данные для графика в формате
        <br />КЛЮЧ=ЗНАЧЕНИЕ
        <br />КЛЮЧ=ЗНАЧЕНИЕ</h3>
    <textarea type="text" name="values" rows="15" cols="50" required></textarea>
    <br>

    <input type="submit" value="Сохранить">
    {% endif %}
</form>
</body>
</html>

charts/templates/charts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'charts/index.css' %}">
    <title>Title</title>
</head>
<body>
<h1>Выберите один из инструментов управления качеством</h1>
{% if diagrams %}
    <ul>
    {% for diagram in diagrams %}
        <li>
            <a href="{% url 'charts:configure' diagram.id%}">{{ diagram.diagram_name }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
{% endif %}
</body>
</html>

charts/templates/charts/pareto.html
<!DOCTYPE HTML>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  {% load static %}
    <link rel="stylesheet" href="{% static 'charts/index.css' %}">
  <title>Диаграмма Парето</title>
</head>
<body>
<div id="chartContainer" style="height: 370px; width: 100%;"></div>
<script defer src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script defer data-items="{{ items }}" data-diagram="{{ diagram }}">
  const div = document.querySelector('#chartContainer')
  div.innerHTML = '<h1>Загрузка ...</h1>'
    const data = document.currentScript.dataset;
    const items = eval(data.items);
    const diagram = data.diagram;
    const dataPoints = items.map(([key, value]) => ({label: key, y: +value}))
window.onload = function () {

const chart = new CanvasJS.Chart("chartContainer", {
	title: { text: diagram },
	axisY: {
		title: "Затраты",
		lineColor: "#4F81BC",
		tickColor: "#4F81BC",
		labelFontColor: "#4F81BC"
	},
	axisY2: {
		title: "Процент",
		suffix: "%",
		lineColor: "#C0504E",
		tickColor: "#C0504E",
		labelFontColor: "#C0504E"
	},
	data: [{
		type: "column",
		dataPoints
	}]
});
chart.render();
createPareto();

function createPareto(){
	var dps = [];
	var yValue, yTotal = 0, yPercent = 0;

	for(var i = 0; i < chart.data[0].dataPoints.length; i++)
		yTotal += chart.data[0].dataPoints[i].y;

	for(var i = 0; i < chart.data[0].dataPoints.length; i++){
		yValue = chart.data[0].dataPoints[i].y;
		yPercent += (yValue / yTotal * 100);
		dps.push({label: chart.data[0].dataPoints[i].label, y: yPercent});
	}

	chart.addTo("data",{type:"line", yValueFormatString: "0.##\"%\"", dataPoints: dps});
	chart.data[1].set("axisYType", "secondary", false);
	chart.axisY[0].set("maximum", yTotal);
	chart.axisY2[0].set("maximum", 100);
}

}
</script>
</body>
</html>

polls/templates/polls/diagram_view.html
<!DOCTYPE HTML>
<html>
<head>
</head>
<body>
<div id="chartContainer" style="height: 370px; width: 100%;"></div>
<script defer src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script defer data-items="{{ items }}" data-diagram="{{ diagram }}">
    const data = document.currentScript.dataset;
    const items = eval(data.items);
    const diagram = data.diagram;
    const dataPoints = items.map(([key, value]) => ({label: key, y: +value}))
window.onload = function () {

const chart = new CanvasJS.Chart("chartContainer", {
	title: { text: diagram },
	axisY: {
		title: "Затраты",
		lineColor: "#4F81BC",
		tickColor: "#4F81BC",
		labelFontColor: "#4F81BC"
	},
	axisY2: {
		title: "Процент",
		suffix: "%",
		lineColor: "#C0504E",
		tickColor: "#C0504E",
		labelFontColor: "#C0504E"
	},
	data: [{
		type: "column",
		dataPoints
	}]
});
chart.render();
createPareto();

function createPareto(){
	var dps = [];
	var yValue, yTotal = 0, yPercent = 0;

	for(var i = 0; i < chart.data[0].dataPoints.length; i++)
		yTotal += chart.data[0].dataPoints[i].y;

	for(var i = 0; i < chart.data[0].dataPoints.length; i++){
		yValue = chart.data[0].dataPoints[i].y;
		yPercent += (yValue / yTotal * 100);
		dps.push({label: chart.data[0].dataPoints[i].label, y: yPercent});
	}

	chart.addTo("data",{type:"line", yValueFormatString: "0.##\"%\"", dataPoints: dps});
	chart.data[1].set("axisYType", "secondary", false);
	chart.axisY[0].set("maximum", yTotal);
	chart.axisY2[0].set("maximum", 100);
}

}
</script>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if diagrams %}
    <ul>
    {% for diagram in diagrams %}
        <li>
            <a href="{% url 'polls:diagram_fill' diagram.id%}">{{ diagram.diagram_name }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
{% endif %}
</body>
</html>